### ISSUE TITLE
Changelog

### ISSUE THREAD

**Issue by dmytro-gokun** [DanmarksAdresser/dawa-autocomplete2#11]
Hi,

first of all, thank you for the great component!

I have a couple of inquiries:

1) I see there was a recent release 1.0.0, but for some reason it is not listed here: https://github.com/DanmarksAdresser/dawa-autocomplete2/releases

2) Is there a changelog or release notes somewhere? I'd like to know what has been changed in this latest release and if there are any breaking changes. This way it is easier for me to update our app to use the new version of the library.

Thanks in advance

**Comment by andershessellund** [comment]
Hi dmytro,

Thanks for your input.

The 1.0.0 tag was mistakenly not uploaded to github. This is now fixed.

I have have added a CHANGELOG.md file to repository.

**Comment by dmytro-gokun** [comment]
Thanks a lot for the update, Anders (Y)
