### ISSUE TITLE
Hvordan anvendes den til autocomplete på matrikelnr / jordstykke?

### ISSUE THREAD

**Issue by osos** [DanmarksAdresser/dawa-autocomplete2#12]
Som heading siger.

Kan jeg anvende dawa-autocomplete på andet end adgangsadresser?

Specifikt ønsker jeg at anvende på søgning efter matrikelnummer / jordstykker. Kan dog ikke se, hvordan den kan konfigureres dertil.

**Comment by osos** [comment]
Jeg kan skifte baseUrl til https://dawa.aws.dk/jordstykker

Den returnerer dog ikke "forslagstekst", men alene "tekst", hvorfor der skal rettet i autocomplete-ui koden.

Derefter virker det som sådan, men efter valgt jordstykke går den dog i uendelig loop med fetch fra registret.

Tænker, at der bør indarbejdes en "type": "Jordstykke"

**Comment by finnjordal** [comment]
dawa-autocomplete2 er målrettet til indtastning af adresser og adgangsadresser - og ikke andre ressourcetyper som jordstykker.

Det er rimeligt enkelt at implementere en autocomplete på andre ressourcetyper ved at anvende komponenten [autocomplete.js](https://www.npmjs.com/package/autocomplete.js) sammen med DAWA's autocomplete funktionalitet.

Du kan finde et eksempel på autocomplete af jordstykker på [GitHub](https://github.com/DanmarksAdresser/autocompleteeksempel).
