### ISSUE TITLE
Option til kun at returnere resultat, men ikke opdatere input felt

### ISSUE THREAD

**Issue by darxmac** [DanmarksAdresser/dawa-autocomplete2#15]
Kan man forestille sig en option der kun returnerer resultatet i `select` callback, men ikke opdaterer inputfeltet. (så jeg selv kan håndtere opdatering af input, og skyde postnummer og by ind i separate felter)

**Comment by andershessellund** [comment]
Jeg forstår det sådan, at du gerne vil kunne styre den tekst der kommer ind i input-feltet, dvs. sådan at postnr og by ikke er med?

Så kan det måske løses ved, at man kan angive en formaterings-funktion som option?

**Comment by andershessellund** [comment]
Vi lukker dette issue, men vil gerne genåbne hvis der kommer et eksempel på et brugsscenarium, der ikke kan håndteres af de nuværende options.
