### ISSUE TITLE
Forbedrings forslag

### ISSUE THREAD

**Issue by notes2c** [DanmarksAdresser/dawa-autocomplete2#2]
Det hænder jo at man kommer til at taste forkert. Og når det sker ville det være lækkert hvis man kunne trykke esc. Dette skulle afstedkomme at indtastningsfeltet blev nulstillet. Det synes jeg ville være lidt lettere en måden man i dag skal nulstille på.

**Comment by andershessellund** [comment]
Dette kan håndteres ved at sætte type="search" på input-feltet. Vi opdaterer vores dokumentation og eksempelkode.
