### ISSUE TITLE
IE11 - "Der opstod en udefineret fejl."

### ISSUE THREAD

**Issue by jakobloekke** [DanmarksAdresser/dawa-autocomplete2#7]
Vi kører Sentry.io-rapportering på et site, der benytter dawa-widget'en, og vi får mange fejl tilbage fra Windows 10/IE11, som ser således ud:

../node_modules/dawa-autocomplete2/dist/dawa-autocomplete2.es.js in Anonymous function at line 1702:1
`

        if (updateInput) {
          inputElm.value = data.inputText;
          inputElm.setSelectionRange(data.caretpos, data.caretpos); // Fejlen er her
        }

        updateInput = false;
        render(suggestionContainerElm, data, function (i) {
          return selectSuggestion(i);
`

Er det en kendt fejl, eller har nogen en idé om, hvad det kan skyldes?

**Comment by andershessellund** [comment]
Jeg kan ikke se hvad der skulle være problemet med den pågældende linje. Den pågældende linje virker også fint og placerer cursoren det rigtige sted i IE11.

Kommer der en mere detaljeret fejlbesked fra sentry?

**Comment by jakobloekke** [comment]
Nej, der er desværre ikke flere detaljer.
Der er en konstant daglig mængde af IE11-brugere (både på Windows 10 og 7), som Sentry rapporterer denne fejl for.
Jeg har heller ikke selv kunnet reproducere den, hverken i browserstack eller på "rigtig" Windows 10-maskine.

> Error: Der opstod en udefineret fejl.
  at Anonymous function(../node_modules/dawa-autocomplete2/dist/js/dawa-autocomplete2.es.js:2537:1)
  at r(../node_modules/@sentry/browser/esm/helpers.js:79:1)
